version: "3"

services:
  db:
    image: postgres
    ports:
      - "5432"
    env_file:
      - ./.env
    volumes:
      - dbdata:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - ./.env
    depends_on:
      - db
    volumes:
      - ./app:/app
    command: >
      bash -c "while !</dev/tcp/db/5432; do sleep 1; done; python app.py"

volumes:
  dbdata:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $PWD/dbdata
